// Generate a runnable Qiskit / qiskit-paulice Python snippet that reproduces
// the current configuration (circuit + device layout + noise + targets + seed).

import type { CouplingMap } from "./types.js";

export interface QiskitExportParams {
  qasm: string;
  edges: CouplingMap;
  targets: number[];
  depol: number;
  readout: number;
  seed: number | null;
  ntries: number;
  useStabilizers: boolean;
}

/** Format a coupling map as a wrapped Python list literal. */
function formatCouplingMap(edges: CouplingMap): string {
  if (edges.length === 0) return "[]";
  const items = edges.map(([a, b]) => `[${a}, ${b}]`);
  const lines: string[] = [];
  for (let i = 0; i < items.length; i += 8) {
    lines.push("    " + items.slice(i, i + 8).join(", ") + ",");
  }
  return "[\n" + lines.join("\n") + "\n]";
}

/** Produce the Qiskit reproduction script. */
export function toQiskitCode(p: QiskitExportParams): string {
  const noiseArgs: string[] = [];
  if (p.depol > 0) noiseArgs.push(`gate_noise=${p.depol}`);
  if (p.readout > 0) noiseArgs.push(`readout_noise=${p.readout}`);
  if (noiseArgs.length === 0) noiseArgs.push("gate_noise=0.001  # set a positive rate");

  const L: string[] = [
    "# Generated by Paulice Online — reproduces this check-picking run in Qiskit.",
    "# Requires:  pip install qiskit-paulice",
    "",
    "import qiskit.qasm2",
    "from qiskit.transpiler import CouplingMap",
    "from qiskit_paulice import add_pauli_checks",
    "from qiskit_paulice.layout import get_check_qubits",
    "from qiskit_paulice.noise_models import NoiseModel",
    "",
    "# --- Circuit ----------------------------------------------------------------",
    'qasm = r"""',
    p.qasm.replace(/\s+$/, ""),
    '"""',
    "circuit = qiskit.qasm2.loads(qasm)",
    "",
    "# --- Device layout ----------------------------------------------------------",
    `coupling_map = CouplingMap(${formatCouplingMap(p.edges)})`,
    "# Physical qubits the payload occupies (identity placement, as in the web app).",
    "layout = list(range(circuit.num_qubits))",
    "# Layout-aware data -> ancilla pairing on this device (for hardware / ISA runs):",
    "paired_targets, paired_ancillas = get_check_qubits(coupling_map, layout)",
    "",
    "# --- Noise model ------------------------------------------------------------",
    `noise_model = NoiseModel(${noiseArgs.join(", ")})`,
    "",
    "# --- Pick checks (windowed search, gamma cost) ------------------------------",
    `target_qubits = [${p.targets.join(", ")}]`,
  ];

  if (p.useStabilizers) {
    L.push(
      "# NOTE: this run used input-stabilizer mode (all-Z), which the public",
      "#   add_pauli_checks does not expose (it protects the measured-qubit logicals).",
      "#   To reproduce stabilizer mode, use the lower-level internal API:",
      "#   from qiskit_paulice._internal import pick_checks",
      '#   pick_checks(rustiq_circuit, target_qubits, [noise], stabilizers="all", ...)',
    );
  }
  if (p.ntries !== 30) {
    L.push(
      `# NOTE: the web app used ntries=${p.ntries} for the windowed search; add_pauli_checks`,
      "#   uses the library default (30) and does not expose this parameter.",
    );
  }

  L.push(
    "results = add_pauli_checks(",
    "    circuit,",
    "    target_qubits,",
    "    noise_model,",
    '    cost="gamma",',
    '    method="windowed",',
    p.seed === null ? "    seed=None," : `    seed=${p.seed},`,
    ")",
    "",
    "# results[k] contains the first k checks; the last has them all.",
    "checked = results[-1]",
    'print(f"{len(checked.check_qubits)} checks committed, gamma cost = {checked.cost}")',
    "print(checked.circuit.draw())",
  );

  return L.join("\n") + "\n";
}
